### ISSUE TITLE
bug: error cuando incio nvim

### ISSUE THREAD

**Issue by manuelduarte077** [TeoDev1611/NeoVim-Config#7]
![Screenshot_10](https://user-images.githubusercontent.com/46093689/142715209-9d72cdb6-cc20-4cb1-997d-283557002e31.png)

![Screenshot_12](https://user-images.githubusercontent.com/46093689/142715250-448f38e9-9820-42b1-8909-ce4a0800e2ef.png)
Hola cuando entro a nvim me sale ese error, por que sera uso el so Windows

alguna idea, para que me pueda ayudar

por cierto tu config esta buenisima

**Comment by TeoDev1611** [comment]
> ![Screenshot_10](https://user-images.githubusercontent.com/46093689/142715209-9d72cdb6-cc20-4cb1-997d-283557002e31.png)
> 
> ![Screenshot_12](https://user-images.githubusercontent.com/46093689/142715250-448f38e9-9820-42b1-8909-ce4a0800e2ef.png) Hola cuando entro a nvim me sale ese error, por que sera uso el so Windows
> 
> alguna idea, para que me pueda ayudar
> 
> por cierto tu config esta buenisima

Hola necesitas instalar python y gcc en el caso de windows usa este comando para chocolatey 

```
choco install python3 mingw64 -y
```

**Comment by manuelduarte077** [comment]
Listo ya quedo eso era
